// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID             pgtype.UUID
	RoomCode       string
	UserID         pgtype.UUID
	QuestionID     pgtype.UUID
	QuestionDataID pgtype.UUID
	AnswerOption   int32
	IsCorrect      bool
	AnswerTime     pgtype.Timestamp
	CreatedOn      pgtype.Timestamp
	UpdatedOn      pgtype.Timestamp
	CreatedBy      string
	UpdatedBy      string
}

type Leaderboard struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	UserID    pgtype.UUID
	Score     float64
	CreatedOn pgtype.Timestamp
	UpdatedOn pgtype.Timestamp
	CreatedBy string
	UpdatedBy string
}

type Question struct {
	ID            pgtype.UUID
	RoomCode      string
	Topic         pgtype.Text
	QuestionCount int32
	QuestionData  []byte
	CreatedOn     pgtype.Timestamp
	UpdatedOn     pgtype.Timestamp
	CreatedBy     string
	UpdatedBy     string
}

type Room struct {
	ID         pgtype.UUID
	RoomCode   string
	RoomName   pgtype.Text
	RoomOwner  pgtype.UUID
	RoomChat   []byte
	RoomMeta   []byte
	RoomLock   bool
	GameType   string
	RoomStatus string
	IsActive   bool
	IsDeleted  bool
	CreatedOn  pgtype.Timestamp
	UpdatedOn  pgtype.Timestamp
	CreatedBy  string
	UpdatedBy  string
}

type RoomMember struct {
	ID               pgtype.UUID
	RoomID           pgtype.UUID
	UserID           pgtype.UUID
	IsBot            bool
	JoinedOn         pgtype.Timestamp
	RoomMemberStatus string
	IsActive         bool
	IsDeleted        bool
	CreatedOn        pgtype.Timestamp
	UpdatedOn        pgtype.Timestamp
	CreatedBy        string
	UpdatedBy        string
}

type User struct {
	ID           pgtype.UUID
	Username     string
	RefreshToken string
	UserType     string
	UserMeta     []byte
	Premium      bool
	IsActive     bool
	IsDeleted    bool
	CreatedOn    pgtype.Timestamp
	UpdatedOn    pgtype.Timestamp
	CreatedBy    string
	UpdatedBy    string
}
