// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID           pgtype.UUID
	RoomID       pgtype.UUID
	UserID       pgtype.UUID
	QuestionID   pgtype.UUID
	AnswerOption int32
	IsCorrect    bool
	AnswerTime   pgtype.Timestamp
	CreatedOn    pgtype.Timestamp
	UpdatedOn    pgtype.Timestamp
	CreatedBy    string
	UpdatedBy    string
}

type Leaderboard struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	UserID    pgtype.UUID
	Score     int32
	CreatedOn pgtype.Timestamp
	UpdatedOn pgtype.Timestamp
	CreatedBy string
	UpdatedBy string
}

type Question struct {
	ID           pgtype.UUID
	RoomID       pgtype.UUID
	QuestionData []byte
	CreatedOn    pgtype.Timestamp
	UpdatedOn    pgtype.Timestamp
	CreatedBy    string
	UpdatedBy    string
}

type Room struct {
	ID          pgtype.UUID
	RoomCode    string
	RoomOwner   pgtype.UUID
	RoomMembers []byte
	RoomChat    []byte
	RoomMeta    []byte
	RoomLock    bool
	IsActive    bool
	IsDeleted   bool
	CreatedOn   pgtype.Timestamp
	UpdatedOn   pgtype.Timestamp
	CreatedBy   string
	UpdatedBy   string
}

type RoomMember struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	UserID    pgtype.UUID
	IsBot     bool
	JoinedOn  pgtype.Timestamp
	IsKicked  bool
	IsActive  bool
	IsDeleted bool
	CreatedOn pgtype.Timestamp
	UpdatedOn pgtype.Timestamp
	CreatedBy string
	UpdatedBy string
}

type User struct {
	ID           pgtype.UUID
	Username     string
	RefreshToken string
	UserType     string
	UserMeta     []byte
	Premium      bool
	IsActive     bool
	IsDeleted    bool
	CreatedOn    pgtype.Timestamp
	UpdatedOn    pgtype.Timestamp
	CreatedBy    string
	UpdatedBy    string
}
