// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rate_limit_query.sql

package dbal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRateLimit = `-- name: CreateRateLimit :exec
INSERT INTO rate_limit (
  id, 
  user_id,
  allowed,
  tries, 
  premium, 
  is_deleted, 
  created_on, 
  updated_on, 
  created_by, 
  updated_by    
)   
VALUES ($1, $2,$3, $4, $5, $6, $7, $8, $9,$10)
`

type CreateRateLimitParams struct {
	ID        string
	UserID    string
	Allowed   int32
	Tries     int32
	Premium   bool
	IsDeleted bool
	CreatedOn pgtype.Timestamp
	UpdatedOn pgtype.Timestamp
	CreatedBy string
	UpdatedBy string
}

func (q *Queries) CreateRateLimit(ctx context.Context, arg CreateRateLimitParams) error {
	_, err := q.db.Exec(ctx, createRateLimit,
		arg.ID,
		arg.UserID,
		arg.Allowed,
		arg.Tries,
		arg.Premium,
		arg.IsDeleted,
		arg.CreatedOn,
		arg.UpdatedOn,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const getRateLimitByUserID = `-- name: GetRateLimitByUserID :many
SELECT id, user_id, allowed, tries, premium, is_deleted, created_on, updated_on, created_by, updated_by FROM rate_limit
WHERE user_id = $1 AND is_deleted = false
`

func (q *Queries) GetRateLimitByUserID(ctx context.Context, userID string) ([]RateLimit, error) {
	rows, err := q.db.Query(ctx, getRateLimitByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateLimit
	for rows.Next() {
		var i RateLimit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Allowed,
			&i.Tries,
			&i.Premium,
			&i.IsDeleted,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRateLimitByUserID = `-- name: UpdateRateLimitByUserID :exec
UPDATE rate_limit
SET
  allowed = $2,
  tries = $3,
  premium = $4,
  is_deleted = $5,
  updated_on = NOW(),
  updated_by = $3
WHERE user_id = $1
`

type UpdateRateLimitByUserIDParams struct {
	UserID    string
	Allowed   int32
	Tries     int32
	Premium   bool
	IsDeleted bool
}

func (q *Queries) UpdateRateLimitByUserID(ctx context.Context, arg UpdateRateLimitByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateRateLimitByUserID,
		arg.UserID,
		arg.Allowed,
		arg.Tries,
		arg.Premium,
		arg.IsDeleted,
	)
	return err
}

const updateRateLimitTriesByUserID = `-- name: UpdateRateLimitTriesByUserID :exec
UPDATE rate_limit
SET 
  tries = $2,
  updated_on = NOW(),
  updated_by = $3
WHERE user_id = $1
`

type UpdateRateLimitTriesByUserIDParams struct {
	UserID    string
	Tries     int32
	UpdatedBy string
}

func (q *Queries) UpdateRateLimitTriesByUserID(ctx context.Context, arg UpdateRateLimitTriesByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateRateLimitTriesByUserID, arg.UserID, arg.Tries, arg.UpdatedBy)
	return err
}
