services:
  # PostgreSQL service
  db:
    image: postgres:15
    container_name: brainwars_pgsql
    environment:
      # todo all these value should come from secret vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brainwars
    volumes:
      - pg_data:/var/lib/postgresql/data # Mount the named volume pg_data into the container at /var/lib/postgresql/data, which is where PostgreSQL stores all of its database files.
    ports:
      - "15432:5432" # Exposing port to access it externally <host_port>:<container_port>

  golang:
    image: godockerdev:v1 #  name  and tag of the image that Docker Compose will assign to this service after building it.
    build:
      #This tells Docker Compose how to build the image.
      context: ../ # this context is only used to build the image
      # the context is the directory where the Dockerfile is located
      dockerfile: ./docker/DockerFile
      target: dev # building dev target in the docker image
    
    container_name: brainwars_go_dev
    depends_on:
      - db
    # bind mounting the source development directory
    volumes:
      - type: bind
        source: ../ # everything present outside of docker folder
        target: /app/
    command: ["sh", "-c", "/app/migrations/migration.sh && air -c .air.toml"]

    # entrypoint: ["/app/migrations/migration.sh"] # running this script to run the migrations
    # this is the command that will be run when the container starts and the entrypoint is executed. which will execute the pgsql migrations 
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pg_data: